### ISSUE TITLE
Works only with `index-` chunk

### ISSUE THREAD

**Issue by benny-noumena** [drwpow/vite-plugin-bundlesize#3]
Hi

For me, it only validates the `index-` chunk but nothing else.

In the example there is an `entrypoints: [{src: 'assets/index-*.js', limit: '120 kB'}]` configuration set but it seems to me that this option is not there anymore.

<img width="1065" alt="image" src="https://github.com/drwpow/vite-plugin-bundlesize/assets/94522639/91a73c32-bca2-406b-8f50-7eef50bfe4d4">

Many Thanks
Ben

**Comment by drwpow** [comment]
Thanks for bringing to my attention. Just pushed an update! This should now work as-expected (or give feedback on error).

**Comment by benny-noumena** [comment]
That is awesome! Many thanks.
